export const skills = [
  { id: 1, name: 'Программирование' },
  { id: 2, name: 'Дизайн' },
  { id: 3, name: 'Веб-программирование' },
  { id: 4, name: 'Создание сайтов' },
  { id: 5, name: 'Администрирование серверов' },
  { id: 6, name: 'Разработка мобильных приложений' },
  { id: 7, name: 'Разработка десктопных приложений' },
  { id: 8, name: 'Роботехника' },
  { id: 9, name: 'Программирование Arduino' },
  { id: 10, name: '3D моделирование' },
  { id: 11, name: 'Разработка десктопных приложение' },
  { id: 12, name: 'Разработка под Android' },
  { id: 13, name: 'Разработка под IOS' },
  { id: 14, name: 'Agile' },
  { id: 15, name: 'PHP' },
  { id: 16, name: 'CI-CD' },
  { id: 17, name: 'CSS' },
  { id: 18, name: 'Docker' },
  { id: 19, name: 'Git' },
  { id: 20, name: 'GoLang' },
  { id: 21, name: 'HTML' },
  { id: 22, name: 'Javascript' },
  { id: 23, name: 'Kotlin' },
  { id: 24, name: 'Laravel' },
  { id: 25, name: 'MongoDB' },
  { id: 26, name: 'MySQL' },
  { id: 27, name: 'NodeJS' },
  { id: 28, name: 'Python' },
  { id: 29, name: 'ReactJS' },
  { id: 30, name: 'Ruby' },
  { id: 31, name: 'Symfony' },
  { id: 32, name: 'TypeScript' },
  { id: 33, name: 'VueJS' },
  { id: 34, name: 'Yii2' },
  { id: 35, name: 'Архитектура приложений' },
  { id: 36, name: 'Микросервисы' },
  { id: 37, name: 'ООП' },
  { id: 38, name: 'Тестирование' },
  { id: 39, name: 'PostgreSQL' },
  { id: 40, name: 'Redis' },
  { id: 41, name: 'ClickHouse' },
  { id: 42, name: 'C' },
  { id: 43, name: 'C++' },
]
